version: '3'
services:
  database:
    image: 'mongo:4.4'
    container_name: 'funterdb'
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ~/database/funterdb:/data/db
    ports:
      - '27017-27019:27017-27019'
  splash:
    image: 'scrapinghub/splash'
    container_name: 'funter_splash'
    ports:
      - '8050:8050'